version: "3.7"

services:
  docs:
    build:
      context: .
    volumes:
      - ".:/code"
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    entrypoint: mkdocs
    command: ["serve", "--dev-addr=0.0.0.0:8000"]
