site_name: Conductor Documentation
theme: windmill
site_description: Concuctor cloud rendering on demand
repo_url: https://github.com/AtomicConductor/AtomicConductor.github.io
remote_branch: master
site_url: https://www.conductortech.com
site_description: Project documentation with Markdown.
site_author: MkDocs Team

# extra:
#   logo:  image/logo.png
nav:
  - Home: index.md
  - Client Tools:
    - Install Client Tools: client_tools/install.md
    - Plugins:
      - Clarisse: client_tools/plugins/clarisse.md
      - Maya: client_tools/plugins/maya.md
      - Nuke: client_tools/plugins/nuke.md
    - Command Line: client_tools/commandline.md
  - Web dashboard: 
    - Jobs View: web_dashboard/jobs_view.md
  - Knowledgebase:
    - Troubleshooting: knowledgebase/troubleshooting.md
    - Instance Types: knowledgebase/instance_types.md
      
  # - Meta: meta.md
 
extra_css:
  - css/autumn.css
  - css/codetabs.css
  - css/extra.css


markdown_extensions:
  - codehilite
  - admonition 
  - meta
  - markdown_fenced_code_tabs:
      template: 'default'
  - toc:
      permalink: true
 
google_analytics: ['UA-97980144-4', 'auto']

copyright: Copyright &copy; 2019 , Conductor Technologies.





# version: Version number to include right under the site name.
# extra.version: Version number to include right under the site name.

# extra.article_nav_top: Set to false to hide the Previous/Next navigation buttons above article contents.

# extra.article_nav_bottom: Set to false to hide the Previous/Next navigation buttons below article contents.