site_name: Conductor Documentation
theme: 'windmill' 

site_description: Conductor cloud rendering on demand
#repo_url: https://github.com/AtomicConductor/conductor_client
remote_branch: master
site_url: https://www.conductortech.com
site_description: Conductor Technical Documentation.
site_author: Conductor Developers 

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started:
    - Overview: getting_started/overview.md    
    - Submitting jobs: getting_started/submitting_jobs.md
    - Managing jobs: getting_started/job_monitoring.md
    - Downloading files: getting_started/downloading_files.md
    - Configuration: getting_started/configuration.md
  - Software:
    - Conductor Companion:
      - Overview: client_tools/companion/overview.md
      - Downloader: client_tools/companion/downloader.md
      - Submitter:
        - Reference: client_tools/companion/submitter.md
        - Examples:
          - Blender Example: client_tools/companion/blender.md
          - Katana Example: client_tools/companion/katana.md
          
          # - Modo Example: client_tools/companion/modo.md
          # - Silhouette Example: client_tools/companion/silhouette.md
          - Arnold Ass Example: client_tools/companion/ass.md
    - Client Applications:  
        - Maya: client_tools/maya.md
        # - Nuke: client_tools/nuke.md
        - Clarisse: client_tools/clarisse.md
        - Conductor CLI: client_tools/cli.md
    - Integrations:
      - Deadline: client_tools/deadline.md      
  # - FAQ: faq.md
extra_css:
  - css/autumn.css
  - css/codetabs.css
  - css/extra.css

markdown_extensions:
  - codehilite
  - admonition
  - meta
  - def_list
  - footnotes
  - markdown_fenced_code_tabs:
      template: 'default'
  - toc:
      permalink: true
      toc_depth: "2-6"
  - pymdownx.snippets:
      base_path: './docs'
  - markdown_captions
  - attr_list



google_analytics: ['UA-97980144-4', 'auto']

copyright: Copyright &copy; 2020 , Conductor Technologies.
